Repository entando-k8s/entando-k8s-cluster-infrastructure-controller, pull requests merged in 2020-10, with the labels that each got.

#12 Eng 872 bumped to latest dependencies
  charts/preview/templates/operator-role.yaml
  pom.xml
  src/main/java/org/entando/kubernetes/controller/clusterinfrastructure/ClusterInfrastructureDeploymentResult.java
  src/main/java/org/entando/kubernetes/controller/clusterinfrastructure/EntandoClusterInfrastructureController.java
  src/main/java/org/entando/kubernetes/controller/clusterinfrastructure/InfrastructureDeployableBase.java
  src/test/java/org/entando/kubernetes/controller/clusterinfrastructure/inprocesstests/DeployEntandoClusterInfrastructureTest.java
  src/test/java/org/entando/kubernetes/controller/clusterinfrastructure/interprocesstests/AddClusterInfrastructureIT.java
Labels: approved, size/M

#13 Eng 1329 bumped to latest operator common
  pom.xml
  src/main/java/org/entando/kubernetes/controller/clusterinfrastructure/EntandoK8SServiceDeployableContainer.java
  src/test/java/org/entando/kubernetes/controller/clusterinfrastructure/inprocesstests/DeployEntandoClusterInfrastructureTest.java
  src/test/java/org/entando/kubernetes/controller/clusterinfrastructure/interprocesstests/AddClusterInfrastructureIT.java
Labels: approved, size/S

#14 Firegloves user into owners
  OWNERS
Labels: size/XS
